### ISSUE TITLE
Integration not working after update to HA 2024.01.0

### ISSUE THREAD

**Issue by f00n** [caronc/ha-ultrasync#32]
After updating to HA 2024.01.0 all of my sensors associated with this integration are not working. 

I get the following error in my HA log aligning with my set refresh interval (1s)

2024-01-13 21:46:30.071 ERROR (MainThread) [custom_components.ultrasync.coordinator] Unexpected error fetching ultrasync data: 'UltraSync' object has no attribute '_Unknown_sequence'
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 300, in _async_refresh
    self.data = await self._async_update_data()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/ultrasync/coordinator.py", line 130, in _async_update_data
    return await self.hass.async_add_executor_job(_update_data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/ultrasync/coordinator.py", line 54, in _update_data
    details = self.hub.details(max_age_sec=0)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/ultrasync/main.py", line 687, in details
    if not self.update(max_age_sec=max_age_sec):
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/ultrasync/main.py", line 672, in update
    if not self._sequence():
           ^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/ultrasync/main.py", line 2199, in _sequence
    return getattr(self, '_{}_sequence'.format(self.vendor))()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'UltraSync' object has no attribute '_Unknown_sequence'

**Comment by f00n** [comment]
My bad, did not realise that my comnav board had crashed.  A reboot of the commav and the integration is working again.
