### ISSUE TITLE
Error on adding integration

### ISSUE THREAD

**Issue by hudak** [caronc/ha-ultrasync#35]
I started with a fresh factory-reset of the alarm panel, then added a dedicated 'homeassistant' user.

```
This error originated from a custom integration.

Logger: custom_components.ultrasync.config_flow
Source: custom_components/ultrasync/config_flow.py:67
integration: UltraSync Alarm Panel
First occurred: 18:55:47 (2 occurrences)
Last logged: 19:05:24

Unexpected exception
Traceback (most recent call last):
  File "/config/custom_components/ultrasync/config_flow.py", line 67, in async_step_user
    await self.hass.async_add_executor_job(
  File "/usr/local/lib/python3.12/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/ultrasync/config_flow.py", line 37, in validate_input
    if not usync.login():
           ^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/ultrasync/main.py", line 224, in login
    if not self._areas(response=response) or not self._zones():
                                                 ^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/ultrasync/main.py", line 1693, in _zones
    return self.process_zones()
           ^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/ultrasync/main.py", line 1255, in process_zones
    return getattr(self, '{}_process_zones'.format(self.vendor))()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/ultrasync/main.py", line 1427, in zerowire_process_zones
    vbank = [int(self._zbank[s][idx:idx + 2], 16) & mask
                 ~~~~~~~~~~~^^^
IndexError: list index out of range
```

**Comment by hudak** [comment]
I identified the issue as an incompatibility with my version of the Zerowire panel. I'll scrape the web server pages and work on a patch.
