### ISSUE TITLE
Hills Reliance R128 with Commnav IndexErrist index out of rangeor: l

### ISSUE THREAD

**Issue by halldave** [caronc/ha-ultrasync#7]
Hi,
I have installed ultrasync from Hacs and get an error in the logfile
2021-01-28 13:55:18 ERROR (MainThread) [custom_components.ultrasync.coordinator] Unexpected error fetching ultrasync data: list index out of range
Traceback (most recent call last):
  File "/snap/home-assistant-snap/123/lib/python3.8/site-packages/homeassistant/helpers/update_coordinator.py", line 144, in async_refresh
    self.data = await self._async_update_data()
  File "/var/snap/home-assistant-snap/123/custom_components/ultrasync/coordinator.py", line 108, in _async_update_data
    return await self.hass.async_add_executor_job(_update_data)
  File "/usr/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/var/snap/home-assistant-snap/123/custom_components/ultrasync/coordinator.py", line 53, in _update_data
    details = self.hub.details(max_age_sec=0)
  File "/root/snap/home-assistant-snap/123/.local/lib/python3.8/site-packages/ultrasync/main.py", line 578, in details
    if not self.update(max_age_sec=max_age_sec):
  File "/root/snap/home-assistant-snap/123/.local/lib/python3.8/site-packages/ultrasync/main.py", line 563, in update
    if not self._sequence():
  File "/root/snap/home-assistant-snap/123/.local/lib/python3.8/site-packages/ultrasync/main.py", line 1498, in _sequence
    return getattr(self, '_{}_sequence'.format(self.vendor))()
  File "/root/snap/home-assistant-snap/123/.local/lib/python3.8/site-packages/ultrasync/main.py", line 1637, in _comnav_sequence
    if area['sequence'] != a_seq[bank]:
IndexError: list index out of range
2021-01-28 13:55:18 WARNING (MainThread) [homeassistant.config_entries] Config entry for ultrasync not ready yet. Retrying in 80 seconds

**when i run the utility I get the same error**

~/.local/bin$ ./ultrasync -c ~/.config/ultrasync -w
2021-01-28 14:36:32 [001] Front Door[R            : Ready
2021-01-28 14:36:32 [001] Dining Room Garage[R    : Ready
2021-01-28 14:36:32 [001] Garage to Laundry       : Ready
2021-01-28 14:36:32 [001] Upstairs Rumpus[M]      : Ready
2021-01-28 14:36:32 [001] Bedroom 2,3,4 [M]       : Ready
2021-01-28 14:36:32 [001] Dining Room[M]          : Ready
2021-01-28 14:36:32 [001] Basement[M]             : Ready
2021-01-28 14:36:32 [001] Under House Door[R]     : Ready
2021-01-28 14:36:32 [001] Large Garage Door[R]    : Ready
2021-01-28 14:36:32 [001] Small Garage Door[R]    : Ready
2021-01-28 14:36:32 [001] Sewing Room[M]          : Ready
2021-01-28 14:36:32 [001] Loft Door [R]           : Ready
2021-01-28 14:36:32 [001] Basement Slide          : Ready
2021-01-28 14:36:32 [001] Family Room Slide       : Ready
2021-01-28 14:36:32 [001] Laundry Door[R]         : Ready
2021-01-28 14:36:32 [001] Master Bedroom[M]       : Ready
2021-01-28 14:36:32 [001] Dining Room Slide W     : Ready
2021-01-28 14:36:32 [001] Dining Room Slide E     : Ready
2021-01-28 14:36:32 [208] Inside House            : Ready
2021-01-28 14:36:32 [000] Garage                  : Ready
---
Traceback (most recent call last):
  File "./ultrasync", line 8, in <module>
    sys.exit(main())
  File "/usr/lib/python3/dist-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python3/dist-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python3/dist-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/home/halldave/.local/lib/python3.8/site-packages/ultrasync/cli.py", line 199, in main
    results = usync.details()
  File "/home/halldave/.local/lib/python3.8/site-packages/ultrasync/main.py", line 578, in details
    if not self.update(max_age_sec=max_age_sec):
  File "/home/halldave/.local/lib/python3.8/site-packages/ultrasync/main.py", line 563, in update
    if not self._sequence():
  File "/home/halldave/.local/lib/python3.8/site-packages/ultrasync/main.py", line 1498, in _sequence
    return getattr(self, '_{}_sequence'.format(self.vendor))()
  File "/home/halldave/.local/lib/python3.8/site-packages/ultrasync/main.py", line 1637, in _comnav_sequence
    if area['sequence'] != a_seq[bank]:
IndexError: list index out of range

I use Ultrasync as an app on the phone, and logging in directly to the comnav web app , the card is plugged into a Hills Reliance 128 zone panel. even though only 18 zones are configured

i have attached my debug file

[20210128144216.ultrasync-dump.zip](https://github.com/caronc/ha-ultrasync/files/5884641/20210128144216.ultrasync-dump.zip)

**Comment by caronc** [comment]
I might have resolved this in the latest update.  Can you give it a try and let me know how it goes for you?

**Comment by halldave** [comment]
Hi Chris

I now see all my Zones and Areas, thanks so much for the update, now I need to have a play

Regards

David

**Comment by caronc** [comment]
Great! I'm glad everything is working. I'm going to close off this ticket now. :slightly_smiling_face:
